import './globals.css'
import AuthContext from './context/AuthContext'
import ToasterContext from './context/ToasterContext'

//import { Inter } from 'next/font/google'


//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Messemger Clone',
  description: 'Generated by Rafael Rivas',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <ToasterContext />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
